variables:
  IMAGE_NAME: kubemod/kubemod-crt

stages:
  - build
  - deploy_latest
  - deploy_tag
  - cleanup

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:latest .

deploy_latest:
  stage: deploy_latest
  only:
    - master
    - tags
  script:
    - docker push $IMAGE_NAME:latest

deploy_tag:
  stage: deploy_tag
  only:
    - tags
  script:
    - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CI_COMMIT_TAG
    - docker push $IMAGE_NAME:$CI_COMMIT_TAG

cleanup:
  stage: cleanup
  script:
    - ./build/cleanup.sh
  when: always
