name: 'Master Workflow'

on:
  push:
    branches:
      - 'master'

jobs:

  deploy:
    name: Deploy latest
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.commits), '[skip ci]') == false

    steps:

      - uses: actions/checkout@v2

      - name: Deploy Latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          KUBEMOD_CRT_IMAGE_VERSION: latest

        run: |
          ./build/deploy-image.sh
