name: 'Tag Workflow'

on:
  push:
    tags:
      - 'v*'

jobs:

  deploy_tag:
    name: Deploy tag
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.commits), '[skip ci]') == false

    steps:

      - uses: actions/checkout@v2

      - name: Deploy Tag
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        run: |
          ./build/deploy-image.sh
